#+TITLE: Advanced Software Engineering
#+AUTHOR: Adolfo Villafiorita
#+STARTUP: showall

This repository contains the material for the "Advanced Software
Engineering" course at UNITN, 2017-2018 edition.

* Syllabus
  - [[Support Material/Syllabus.docx]]

* Schedule:
  - Monday 14:10-15:50 Room B104
  - Wednesdary 14:10-15:50 Room B104

* Lesson 1. Introduction
  <2017-09-13 Wed 14:00 - 16:00>

  Administrative matters (exam, getting in touch, etc), entry
  questionnaire, and a motivating example, which describes why
  developing software is complex.

  Slides:

  - [[Slides/01-Introduction-2017.odp]]
  - [[Slides/02 - Motivating Example.odp]]

* Lesson 2. Configuration Management
  <2017-09-18 Mon 14:00-16:00>

  Configuration Management helps us ensuring the coherency of a system
  over time

  - [[Slides/03 - Configuration Management.odp]]

* Lesson 3. Configuration Management
  <2017-09-20 Wed 14:00-16:00>
  
  More on Configuration Management and on Git.  The branching
  development model and the merging (nightmare, if you don't do things
  right).

  - [[Slides/04-Git.odp]]

* Lesson 4. Ruby Tutorial
  <2017-09-20 Wed 16:00-18:00>

  - [[Tutorials/01_ruby_basics_1.md]] Ruby basics (part 1)

* Lesson 5. More Ruby
  <2017-09-25 Mon 14:00-16:00>

  - [[file:./Teams/assignment.org][Calendario e Specifica Assignment]]

* Lesson 6. Object Oriented Programming
  <2017-09-27 Wed 14:00-18:00>

  - [[file:Slides/05-StructuredProgramming.odp][Object Oriented Programming]]
